### ISSUE TITLE
Email issue

### ISSUE THREAD

**Issue by peppeska** [davidegiunchi/send-bacula-backup-report#1]
Hi !

I have a problem with the email.

in the file "/etc/bacula/send_bacula_backup_report.conf" I wrote:

`
$email_from='realemail@companydomain.it';

$email_to='mypersonalemail@companydomain.it';

$email_subject="Bacula Backup report of $mday/$mon/$year";
`

But when try "/etc/bacula/scripts/send_bacula_backup_report.pl 1" I don't recive email and from log I have

`
Feb 19 13:07:19 localhost  postfix/qmgr[1991]: 2B31E20037: from=<root@localhost .localdomain>, size=17383, nrcpt=1 (queue active)
Feb 19 13:07:19 localhost postfix/smtp[4131]: connect to aspmx.l.google.com[2a00:1450:400c:c09::1a]:25: Network is unreachable

Feb 19 13:07:19 localhost  postfix/smtp[4131]: 2B31E20037: enabling PIX workarounds: disable_esmtp delay_dotcrlf for aspmx.l.google.com[64.233.167.27]:25

Feb 19 13:07:19 localhost  postfix/smtp[4131]: 2B31E20037: to=mypersonalemail@companydomain.it, relay=aspmx.l.google.com[64.233.167.27]:25, delay=0.2, delays=0.04/0.01/0.13/0.02, dsn=5.1.2, status=bounced (host aspmx.l.google.com[64.233.167.27] said: 553-5.1.2 The sender address root@localhost.localdomain is 553 5.1.2 not a valid RFC-5321 address. 202si12330378wmy.77 - gsmtp (in reply to MAIL FROM command))

Feb 19 13:07:19 localhost  postfix/cleanup[4129]: 5F03F20043: message-id=<20160219120719.5F03F20043@localhost .localdomain>

Feb 19 13:07:19 localhost  postfix/bounce[4132]: 2B31E20037: sender non-delivery notification: 5F03F20043

Feb 19 13:07:19 localhost  postfix/qmgr[1991]: 5F03F20043: from=<>, size=19874, nrcpt=1 (queue active)

Feb 19 13:07:19 localhost  postfix/qmgr[1991]: 2B31E20037: removed

Feb 19 13:07:19 localhost  postfix/local[4133]: 5F03F20043: to=<root@localhost .localdomain>, relay=local, delay=0.01, delays=0/0.01/0/0, dsn=2.0.0, status=sent (delivered to mailbox)

Feb 19 13:07:19 localhost  postfix/qmgr[1991]: 5F03F20043: removed
`

--> The sender address root@localhost.localdomain is 553 5.1.2 not a valid RFC-5321 address

**Comment by davidegiunchi** [comment]
The "$email_from" is the field "From:" of the email, not the "Envelope From".
The envelope from is set by your local MTA (usually postfix or exim), postfix use the "hostname" variable plus the unix user that send the email.
To better fix the problem, you need to **change the hostname** of the server to a valid one. Please note that localhost.localdomain maybe it's invalid and will cause various problems other than send-bacula-backup-report.

If you can't or you need a **workaround**, you can add the following code:

> MIME::Lite->send('sendmail', SetSender=>1);

on the line 129 of send_bacula_backup_report.pl, just before the line "MIME::Lite->send('sendmail', SetSender=>0);".

Regards

**Comment by peppeska** [comment]
hi!
yes! on line 129, just before "my $msg = MIME::Lite->new" !

It's work! thanks!
